name: Ottotext
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  Ottotext:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Sources
    resources:
      - path: Resources
    info:
      path: Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ottotext
        INFOPLIST_FILE: Info.plist
